import os
import time
import numpy as np
import pandas as pd
from datetime import datetime
from fastapi import FastAPI
import threading
import smtplib
from email.mime.text import MIMEText

from sklearn.ensemble import IsolationForest
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

import torch
import torch.nn as nn

# ======================
# DEVICE
# ======================
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ======================
# CONFIG
# ======================
NUM_ZONES = 10
HOUSES_PER_ZONE = 5
HISTORY_LIMIT = 200
LSTM_WINDOW = 20
EPOCHS = 2
alpha = 0.05

LOG_FILE = "zone_risk_stream.csv"

# ======================
# ALERT CONTROL (ANTI-SPAM)
# ======================
last_alert = {}

# ======================
# EMAIL ALERT FUNCTION
# ======================
def send_email_alert(zone, risk):
    try:
        msg = MIMEText(f"""
🚨 GRID EYE - CRITICAL ALERT 🚨

ZONE: {zone}
RISK SCORE: {risk}

SYSTEM ANALYSIS:
This zone is showing abnormal electrical behavior.

POSSIBLE CAUSES:
- External Power Theft
- Illegal Tapping
- Sudden Load Spike
- Fault / Overload

ACTION:
Immediate inspection recommended.

This alert is generated by the Zone Risk Engine.
""")

        msg["Subject"] = f"⚡ ALERT | {zone} | RISK {risk}"
        msg["From"] = "grideyezoneriskengine@gmail.com"
        msg["To"] = "grideyezoneriskengine@gmail.com"

        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login("grideyezoneriskengine@gmail.com", "kakpscdfgtmndvyl")
        server.send_message(msg)
        server.quit()

        print("✅ EMAIL ALERT SENT")

    except Exception as e:
        print("❌ EMAIL FAILED:", e)

# ======================
# MODEL
# ======================
class LSTMModel(nn.Module):
    def __init__(self, input_size):
        super().__init__()
        self.lstm = nn.LSTM(input_size, 32, batch_first=True)
        self.fc = nn.Linear(32, 1)

    def forward(self, x):
        out, _ = self.lstm(x)
        return self.fc(out[:, -1, :])

# ======================
# STATE
# ======================
def create_state():
    model = LSTMModel(12).to(DEVICE)
    return {
        "model": IsolationForest(contamination=0.15),
        "lstm": model,
        "optimizer": torch.optim.Adam(model.parameters(), lr=0.001),
        "loss_fn": nn.MSELoss(),
        "history": [],
        "baseline": None,
        "cluster_prev": 0
    }

ZONES = {f"Z{i}": create_state() for i in range(NUM_ZONES)}
scaler = StandardScaler()

# ======================
# LOGGING
# ======================
def log_data(zone, loads, total, risk):
    try:
        row = {
            "time": datetime.now(),
            "zone": zone,
            "total": float(total),
            "risk": float(risk)
        }

        for i, val in enumerate(loads):
            row[f"h{i+1}"] = float(val)

        df = pd.DataFrame([row])

        df.to_csv(
            LOG_FILE,
            mode='a',
            header=not os.path.exists(LOG_FILE),
            index=False
        )
    except Exception as e:
        print("LOG ERROR:", e)

# ======================
# FEATURES
# ======================
def build_features(loads, total):
    imbalance = abs(sum(loads) - total)
    ratios = [l/total if total else 0 for l in loads]

    return np.array([
        *loads,
        total,
        imbalance,
        datetime.now().hour,
        *ratios
    ], dtype=float)

# ======================
# LSTM
# ======================
def lstm_predict(state):
    try:
        hist = np.array(state["history"])

        if len(hist) < LSTM_WINDOW + 5:
            return 0

        X, y = [], []

        for i in range(len(hist) - LSTM_WINDOW):
            X.append(hist[i:i+LSTM_WINDOW])
            y.append(hist[i+LSTM_WINDOW][6])

        X = torch.tensor(X, dtype=torch.float32).to(DEVICE)
        y = torch.tensor(y, dtype=torch.float32).to(DEVICE)

        model = state["lstm"]
        opt = state["optimizer"]
        loss_fn = state["loss_fn"]

        for _ in range(EPOCHS):
            opt.zero_grad()
            out = model(X).squeeze()
            loss = loss_fn(out, y)
            loss.backward()
            opt.step()

        seq = torch.tensor(hist[-LSTM_WINDOW:], dtype=torch.float32).unsqueeze(0).to(DEVICE)
        return float(model(seq).item())

    except:
        return 0

# ======================
# ENGINE
# ======================
def process(zone, loads, total):
    s = ZONES[zone]

    f = build_features(loads, total)
    s["history"].append(f)

    if len(s["history"]) > HISTORY_LIMIT:
        s["history"].pop(0)

    data = np.array(s["history"])

    if s["baseline"] is None:
        s["baseline"] = f
    else:
        s["baseline"] = alpha*f + (1-alpha)*s["baseline"]

    deviation = np.linalg.norm(f - s["baseline"])

    if len(data) > 10:
        s["model"].fit(data)

    anomaly = 0
    if len(data) > 10:
        anomaly = int(s["model"].predict([f])[0] == -1)

    cluster = 0
    if len(data) > 15:
        try:
            scaled = scaler.fit_transform(data)
            labels = DBSCAN().fit_predict(scaled)
            cluster = np.sum(labels == -1) / len(labels)
        except:
            cluster = 0

    drift = abs(cluster - s["cluster_prev"])
    s["cluster_prev"] = cluster

    future = lstm_predict(s)

    risk = np.tanh(anomaly + deviation/10 + cluster + drift + future/6)
    risk = round(float(risk), 2)

    # ======================
    # SMART ALERT SYSTEM (COOLDOWN)
    # ======================
    if risk > 0.8:
        now = time.time()
        if zone not in last_alert or now - last_alert[zone] > 60:
            send_email_alert(zone, risk)
            last_alert[zone] = now

    return risk

# ======================
# FASTAPI
# ======================
app = FastAPI()

@app.post("/sensor")
def sensor_input(zone: str, loads: list, total: float):
    risk = process(zone, loads, total)
    return {"zone": zone, "risk": risk}

@app.get("/status")
def status():
    return {"zones": list(ZONES.keys())}

# ======================
# SIMULATION
# ======================
def simulate():
    while True:
        try:
            for zone in ZONES:
                loads = np.random.uniform(2, 4, HOUSES_PER_ZONE)
                total = float(np.sum(loads) + np.random.uniform(0, 2))

                risk = process(zone, loads, total)

                log_data(zone, loads, total, risk)

                print(f"{zone} | RISK: {risk}")

            print("\n--- SYSTEM RUNNING ---\n")
            time.sleep(5)

        except Exception as e:
            print("ERROR:", e)

# ======================
# RUN
# ======================
if __name__ == "__main__":
    threading.Thread(target=simulate, daemon=True).start()

    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8001)
